language: r
r: 
  - 3.6.2
  
sudo: required

cache:
  directories:
  - $HOME/.local/share/renv
  - $TRAVIS_BUILD_DIR/renv/library

before_install:
- sudo add-apt-repository -y ppa:opencpu/jq
- sudo apt-get update
- sudo apt-get install libudunits2-dev libproj-dev libgdal-dev libv8-3.14-dev libprotobuf-dev protobuf-compiler libjq-dev 

install:
  - Rscript -e "renv::restore()"

deploy:
  provider: script
  script: 
  - R -f deploy.R
  skip_cleanup: true
  on: 
    branch: 
    - master
    - develop
    repo: adamrobinson361/google_geocode